pipeline {
    agent any

    tools {
        nodejs 'NodeJS-22'
    }

    environment {
        COMPOSE_FILE = 'docker-compose.prod.yml'
    }

    stages {

        stage('Checkout') {
            steps {
                echo '========== CHECKOUT =========='
                checkout scm
            }
        }

        stage('Verify Environment') {
            steps {
                echo '========== VERIFY ENVIRONMENT =========='

                bat 'git --version'
                bat 'node -v'
                bat 'npm -v'
                bat 'docker --version'
                bat 'docker compose version'
            }
        }

        stage('Install Frontend Dependencies') {
            steps {
                dir('seed-main') {
                    bat 'npm install'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('seed-main') {
                    bat 'npm run build'
                }
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                dir('server') {
                    bat 'npm install'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                bat "docker compose -f %COMPOSE_FILE% build"
            }
        }

        stage('Deploy Application') {
            steps {
                bat "docker compose -f %COMPOSE_FILE% up -d"
            }
        }

        stage('Verify Containers') {
            steps {
                bat "docker ps"
            }
        }
    }

    post {

        success {
            echo '======================================='
            echo ' Seedify deployed successfully!'
            echo '======================================='
        }

        failure {
            echo '======================================='
            echo ' Pipeline Failed!'
            echo '======================================='
        }

        always {
            cleanWs()
        }
    }
}