pipeline {
    agent any

    tools {
        nodejs 'NodeJS-22'
    }

    environment {
        COMPOSE_FILE = 'seed123/docker-compose.prod.yml'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Environment') {
            steps {
                bat 'git --version'
                bat 'node -v'
                bat 'npm -v'
                bat 'docker --version'
                bat 'docker compose version'
            }
        }

        stage('Install Frontend Dependencies') {
            steps {
                dir('seed123/seed-main') {
                    bat 'npm install'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('seed123/seed-main') {
                    bat 'npm run build'
                }
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                dir('seed123/server') {
                    bat 'npm install'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                bat 'docker compose -f seed123/docker-compose.prod.yml build'
            }
        }

        stage('Deploy Application') {
            steps {
                bat 'docker compose -f seed123/docker-compose.prod.yml up -d'
            }
        }

        stage('Verify Containers') {
            steps {
                bat 'docker ps'
            }
        }
    }

    post {
        success {
            echo "====================================="
            echo "Seedify Pipeline Completed Successfully"
            echo "====================================="
        }

        failure {
            echo "====================================="
            echo "Pipeline Failed"
            echo "====================================="
        }

        always {
            cleanWs()
        }
    }
}