sonar.projectKey=seedify
sonar.projectName=Seedify
sonar.projectVersion=1.0

# Source folders
sonar.sources=server,seed-main/src

# Exclude generated files
sonar.exclusions=**/node_modules/**,**/dist/**

# Encoding
sonar.sourceEncoding=UTF-8